version: "3.8"

services:
  reservations:
    build:
      context: .
      dockerfile: ./apps/reservations/Dockerfile
      target: development
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: pnpm run start:dev reservations
  auth:
    build: 
      context: .
      dockerfile: ./apps/auth/Dockerfile
      target: development
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=development
    env_file:
      - .env
    command: pnpm run start:dev auth

  mongo:
    image: mongo
    restart: always
    ports:
      - "27017:27017"  # Expose MongoDB to your local machine
    volumes:
      - mongo-data:/data/db  # Persist MongoDB data
volumes:
  mongo-data:
